// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVf4Ia8Nhq1NiHKD9VLM_AYT9FvKCd_hA',
    appId: '1:498273919331:web:69b56caf64056d0e5ff356',
    messagingSenderId: '498273919331',
    projectId: 'studienarbeit-focusapp',
    authDomain: 'studienarbeit-focusapp.firebaseapp.com',
    storageBucket: 'studienarbeit-focusapp.appspot.com',
    measurementId: 'G-2M5XP0WNY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-aKtaW0yOkgGEppr4L4ARVesv3l7p8ws',
    appId: '1:498273919331:android:325ff250552c9a685ff356',
    messagingSenderId: '498273919331',
    projectId: 'studienarbeit-focusapp',
    storageBucket: 'studienarbeit-focusapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnQ5inUnll1RU9DgSUvRfyR89Qkc0ssv8',
    appId: '1:498273919331:ios:e1f4112b9691d4525ff356',
    messagingSenderId: '498273919331',
    projectId: 'studienarbeit-focusapp',
    storageBucket: 'studienarbeit-focusapp.appspot.com',
    iosBundleId: 'com.focusapp.studienarbeitFocusApp',
  );
}
